# Generated by Django 3.0 on 2021-09-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='dt',
        ),
    ]
