# Generated by Django 3.0 on 2021-09-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_remove_blogmodel_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='dt',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
    ]
